FROM tomcat:7.0.70

ENV EPSOS_PROPS_PATH /opt/epsos-configuration/
ENV JAVA_OPTS -Djava.security.egd=file:/dev/./urandom
#RUN sed -i "s/httpredir.debian.org/mirrors.digitalocean.com/" /etc/apt/sources.list


EXPOSE 8080

